#!/bin/bash

## install packages
if ! [[ -x "$(command -v git)"&& -x "$(command -v docker)"  && -x "$(command -v docker-compose)" ]]; then
  sudo apt-get update && \
      sudo apt-get install -y git docker.io docker-compose && \
      sudo usermod -aG docker $USER && \
      git clone https://github.com/dddlab/google-faculty-institute-demo.git && \
      echo "Cloned https://github.com/dddlab/google-faculty-institute-demo repository" && \
      echo "Re-login and run ~/google-faculty-institute-demo/setup.sh"
  exit 1
fi

[ -d .dddlab/keys ] || mkdir -p .dddlab/keys

## Self-signed certificates can be generated according to
## https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication

openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout .dddlab/keys/mykey.key \
    -out .dddlab/keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F" \
    && chmod a+r .dddlab/keys/mykey.key


## utility for hashing notebook password 
curl -fsSL https://github.com/dddlab/jupyter-passwd/releases/download/v0.0.1.6/hash-password \
    --output .dddlab/hash-password && \
    chmod u+x .dddlab/hash-password

# https://github.com/docker/compose/issues/4223#issuecomment-280077263
# https://docs.docker.com/compose/environment-variables/

cat <<EOF > .env
## generated by setup.sh
## variables for docker-compose

HOST_DIR=${PWD}
CERT_DIR=${PWD}/.dddlab/keys
PASSWD=$(.dddlab/hash-password)
EOF

cat <<EOF > .env_file
## generated by setup.sh
## container instance variables
## i.e. environment section in docker-compose.yml

NB_UID=$(id -u)
NB_GID=$(id -g)
JUPYTER_ENABLE_LAB=yes
GRANT_SUDO=yes
EOF

